services:
  - type: web
    name: school-counseling-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: COUNSELOR_PHONE
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
    autoDeploy: true
